<?php


/**
 * @file spiderweb.module
 */

/**
 * Grab one topic from Spiderweb. Raw output will be returned.
 *
 * @param $pid
 *   The Post ID of the first post in the topic.
 *
 * @return
 *   string of HTML markup.
 */
function spiderweb_grab_topic($pid, $page = 'all') {
  module_load_include('inc', 'spiderweb', 'spiderweb.http');
  $form = array(
    'ubb' => 'showflat',
    'Number' => $pid,
    'page' => $page,
  );
  $response = spiderweb_get($form);
  return $response->data;
}

/**
 * Index a complete forum.
 * @TODO: Move this to the piperbot, because grabbing and parsing should be distinct.
 *
 * @param $fid
 *   The forum ID that should be indexed.
 * @param $max_pages
 *   [optional] How many pages should be grabbed at most. If not set, all pages will be grabbed.
 *   Number of topics per page is determined by the user account this module logs in as.
 *   The maximum number is 99.
 *
 * @return
 *   An array of topic objects.
 */
function spiderweb_index_forum($fid, $max_pages = 0) {
  module_load_include('inc', 'spiderweb', 'spiderweb.parse');
  // update this value later.
  $total_pages = 1;
  $topics = array();
  for ($i = 1; $i <= $total_pages; $i++) {
    $data        = spiderweb_grab_forum_page($fid, $i);
    $forum       = spiderweb_parse_forum($data);
    $total_pages = $max_pages ? min($max_pages, $forum->pages) : $forum->pages;
    $topics += $forum->topics;
  }

  foreach ($topics as & $topic) $topic->forum = $fid;
  return $topics;
}

/**
 * Grab a single page of a forum.
 *
 * @param $forum
 *   The ID number of the forum to acquire.
 * @param $page
 *   The page number
 *
 * @return
 *   The page as a string of HTML markup.
 */
function spiderweb_grab_forum_page($forum, $page) {
  module_load_include('inc', 'spiderweb', 'spiderweb.http');
  $form = array(
    'ubb' => 'postlist',
    'Board' => $forum,
    'page' => $page,
    'o' => 'all', // avoid date cut-off.
  );

  $response = spiderweb_get($form);
  return $response->data;
}

/**
 * Grab the front page of the whole board.
 *
 * @return
 *   string of HTML markup.
 */
function spiderweb_grab_main_page() {
  module_load_include('inc', 'spiderweb', 'spiderweb.http');
  $form = array('ubb' => 'cfrm');
  $response = spiderweb_get($form);
  return $response->data;
}

/**
 * Grab a user page.
 *
 * @param $uid
 *   int the user ID to be requested.
 *
 * @return
 *   string a page of HTML markup
 */
function spiderweb_grab_user($uid) {
  module_load_include('inc', 'spiderweb', 'spiderweb.http');
  $form = array(
    'ubb' => 'showprofile',
    'User' => $uid,
  );
  $response = spiderweb_get($form);
  return $response->data;
}

