<?php
// $Id$


/**
 * @file ppp_display.module
 * General hooks as well as helper functions for displaying PPP.
 */

/**
 * DB-less pager. We need this for PDO.
 */
function ppp_pager_args($limit = 10, $element = 0, $total = 10) {
  global $pager_page_array, $pager_total, $pager_total_items;
  $page = isset($_GET['page']) ? $_GET['page'] : '';

  $pager_total_items[$element] = $total;

  $pager_total[$element] = ceil($pager_total_items[$element] / $limit);
  $pager_page_array[$element] = max(0, min((int)$pager_page_array[$element], ((int)$pager_total[$element]) - 1));

  return array('start' => $pager_page_array[$element] * $limit, 'count' => $limit);
}

/**
 * Implementation of hook_menu()
 */
function ppp_display_menu() {
  $menu['archives'] = array(
    'title' => 'Archives',
    'description' => 'View all forums',
    'page callback' => 'ppp_display_page_main',
    'access arguments' => array('view archived content'),
    'file' => 'ppp_display.pages.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  $menu['forum/%ppp_forum'] = array(
    'title callback' => 'ppp_display_title_forum',
    'title arguments' => array(1),
    'page callback' => 'ppp_display_page_forum',
    'page arguments' => array(1),
    'access callback' => 'ppp_display_access_forum',
    'access arguments' => array(1),
    'file' => 'ppp_display.pages.inc',
    'type' => MENU_CALLBACK,
  );

  $menu['topic/%ppp_topic'] = array(
    'title callback' => 'ppp_display_title_topic',
    'title arguments' => array(1),
    'page callback' => 'ppp_display_page_topic',
    'page arguments' => array(1),
    'access callback' => 'ppp_display_access_topic',
    'access arguments' => array(1),
    'file' => 'ppp_display.pages.inc',
    'type' => MENU_CALLBACK,
  );

  return $menu;
}

/**
 * Implementation of hook_perm()
 */
function ppp_display_perm() {
  return array(
    'view archived content' => t('View any public forum, topic or post in the archives.'),
    'view classified content' => t('View content that is not public on the original forum.'),
  );
}

/**
 * Implementation of hook_theme()
 */
function ppp_display_theme() {
  $theme['ppp_display_forum_name'] = array(
    'arguments' => array('forum' => NULL),
  );
  $theme['ppp_display_topiclist'] = array(
    'arguments' => array('topics' => NULL, 'forum' => NULL),
  );
  $theme['ppp_display_postlist'] = array(
    'arguments' => array('posts' => NULL, 'topic' => NULL, 'forum' => NULL),
  );
  $theme['ppp_display_forum_last'] = array(
    'arguments' => array('post' => NULL),
  );
  return $theme;
}

/**
 * Determine whether the current user may view a certain forum or topic
 *
 * @param $forum
 *   The number of the forum that is being requested, or the forum the topic is in.
 *
 * @return
 *   A user access boolean.
 */
function ppp_display_access_forum($forum) {
  $mod_boards = variable_get('ppp_classified_fora', array());

  if (!empty($mod_boards[$forum->fid])) {
    return user_access('view classified content');
  }
  else {
    return user_access('view archived content');
  }
}

function ppp_forum_load($fid) {
  module_load_include('inc', 'ppp_data', 'ppp_data.load');
  return ppp_data_load_forum($fid);
}

function ppp_display_title_forum($forum) {
  return t('Forum: !name', array('!name' => $forum->name));
}